[app]
name = "REDSTOP Collect Server"
owner = "KTJ, CYJ, AJH"

[static]
type = "DEFAULT" #default is normal static

[server]
addr = ":7000"
domain_web = "localhost:7000/"
domain_api = "localhost:7000/api"
domain_web_socket = "localhost:7000/ws"

[testServer]
test_domain = "http://localhost:3000/"